export {default as HomeView} from './HomeView.vue'
export {default as RegisterView} from './RegisterView.vue'
export {default as LoginView} from './LoginView.vue'
export {default as DocumentView} from './DocumentView.vue'
export {default as NewsView} from './NewsView.vue'
export {default as NewsDetailsView} from './NewsDetailsView.vue'