export {default as Navbar } from './Navbar.vue'
export {default as Register} from './Register.vue'
export {default as Login} from './Login.vue'
export {default as Document} from './Document.vue'
export {default as News} from './News.vue'
export {default as NewsDetails} from './NewsDetails.vue'